function check() {
    let g1;
    let g2;
    let g3;
    let g4;
    let g5;
    let g6;
    let g7;
    let g8;
    let g9;
    let g10;
    let g111
    let g12;
    let g13;
    let g14;
    let g15;
    let g16;
    let g17;
    let g18;
    let g19;
    let g20;
    let g21;
    let g22;
    let g23;
    //storing values
    g1=document.getElementById("d1").value;
    g2=document.getElementById("d2").value;
    g3=document.getElementById("d3").value;
    g4=document.getElementById("d4").value;
    g5=document.getElementById("d5").value;
    g6=document.getElementById("d6").value;
    g7=document.getElementById("d7").value;
    g8=document.getElementById("d8").value;
    g9=document.getElementById("d9").value;
    g10=document.getElementById("d10").value;
    g11=document.getElementById("d11").value;
    g12=document.getElementById("d12").value;
    g13=document.getElementById("d13").value;
    g14=document.getElementById("d14").value;
    g15=document.getElementById("d15").value;
    g16=document.getElementById("d16").value;
    g17=document.getElementById("d17").value;
    g18=document.getElementById("d18").value;
    g19=document.getElementById("d19").value;
    g20=document.getElementById("d20").value;
    g21=document.getElementById("d21").value;
    g22=document.getElementById("d22").value;
    g23=document.getElementById("d23").value;

    console.log(g1);
    console.log(g2);
    console.log(g3);
    console.log(g4);
    console.log(g5);
    console.log(g6);
    console.log(g7);
    console.log(g8);
    console.log(g9);
    console.log(g10);
    console.log(g11);
    console.log(g12);
    console.log(g13);
    console.log(g14);
    console.log(g15);
    console.log(g16);
    console.log(g17);
    console.log(g18);
    console.log(g19);
    console.log(g20);
    console.log(g21);
    console.log(g22);
    console.log(g23); 
    
    //showing values
    document.getElementById("fname").innerHTML=g1;
    document.getElementById("fmname").innerHTML=g2;
    document.getElementById("flname").innerHTML=g3;
    document.getElementById("fmail").innerHTML=g4;
    document.getElementById("fpd").innerHTML=g5;
    document.getElementById("fdob").innerHTML=g6;
    document.getElementById("fgen").innerHTML=g7;
    document.getElementById("fadd").innerHTML=g8;
    document.getElementById("fpc").innerHTML=g9;
    document.getElementById("fmbno").innerHTML=g10;
    document.getElementById("fadno").innerHTML=g11;
    document.getElementById("fpcno").innerHTML=g12;
    document.getElementById("fcy").innerHTML=g13;
    document.getElementById("fsts").innerHTML=g14;
    document.getElementById("fssc mr").innerHTML=g15;
    document.getElementById("fsc name").innerHTML=g16;
    document.getElementById("fgd").innerHTML=g17;
    document.getElementById("finter mr").innerHTML=g18;
    document.getElementById("fclgname").innerHTML=g19;
    document.getElementById("fgd").innerHTML=g20;
    document.getElementById("fgrdu").innerHTML=g21;
    document.getElementById("fclgname").innerHTML=g22;
    document.getElementById("fgd").innerHTML=g23;
}

